import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login');
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).fill('Admin');
  await page.getByRole('textbox', { name: 'Username' }).press('Tab');
  await page.getByRole('textbox', { name: 'Password' }).fill('admin123');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('link', { name: 'Admin' }).click();
  await page.getByRole('listitem').filter({ hasText: 'Job' }).locator('i').click();
  await page.getByRole('menuitem', { name: 'Job Titles' }).click();
  await page.getByRole('button', { name: ' Add' }).click();
  await page.getByRole('textbox').nth(1).click();
  await page.getByRole('textbox').nth(1).fill('AutomationEngineer');
  await page.getByRole('textbox', { name: 'Type description here' }).click();
  await page.getByRole('textbox', { name: 'Type description here' }).click();
  await page.getByRole('textbox', { name: 'Type description here' }).fill('Automation & Manual Testing: \nSelenium Web Driver using JAVA, \nSelenium IDE, Test NG & POM, BDD With Cucumber Framework  MAVEN\nCypress with page object model using Java script is in progress.\nIntegration Testing :\nREST  API testing using POSTMAN, Swagger, Exposure with JSON, Using Different Methods and performing CRUD operations on endpoints\nWriting test cases and postman assertions with JavaScript\nRunning collection with multiple instances\nMocking APIs\nNewman for CI/CD with Jenkins-Scheduling, email notifications, Build run\nGenerating html reports with Newman \nAPI Automation testing with REST Assured library- JAVA\n \n\n\nProgramming Skills: Core Java \nOperating Systems: Windows \nCoding Platforms: Eclipse, IntelliJ \nDatabase: Basic Knowledge in MY SQL Server with SQL \nPackages: Microsoft Office\n Others: Git, Git Hub, Jenkins \nProject Management tool: JIRA, Confluence, Xray\n\nTesting tools(Manual+ Automation)-2021-\n       Mind Q Systems Pvt Ltd\nSQL-2022- Stockholm IT Academy\nSelenium-Web UI Automation Testing-2022-Stockholm IT Academy\nLearn Cucumber BDD with Java(Selenium Framework)-2022-Udemy\nISTQB- Software Testing Foundation level Scored \n37 out of 40\nThe ISTQB® Foundation Level Agile Tester (CTFL-AT)');
  await page.getByText('Browse').click();
  await page.getByRole('textbox', { name: 'Type description here' }).click();
  await page.getByRole('textbox', { name: 'Type description here' }).fill('Automation & Manual Testing: \nSelenium Web Driver using JAVA, \nSelenium IDE, Test NG & POM, BDD With Cucumber Framework  MAVEN\nCypress with page object model using Java script is in progress.\nIntegration Testing :\nREST  API testing using POSTMAN, Swagger, Exposure with JSON, Using Different Methods and performing CRUD operations on endpoints\nWriting test cases and postman assertions with JavaScript\nRunning collection with multiple instances\nMocking APIs\nNewman for CI/CD with Jenkins-Scheduling, email notifications, Build run\nGenerating html reports with Newman \nAPI Automation testing with REST Assured library- JAVA\n \n\n\nProgramming Skills: Core Java \nOperating Systems: Windows \nCoding Platforms: Eclipse, IntelliJ \nDatabase: Basic Knowledge in MY SQL Server with SQL \nPackages: Microsoft Office\n Others: Git, Git Hub, Jenkins \nProject Management tool: JIRA, Confluence, Xray\n\nTesting tools(Manual+ Automation)-2021-\n       Mind Q Systems Pvt Lt\n37 out of 40\nThe ISTQB® Foundation Level Agile Tester (CTFL-AT)');
  await page.getByRole('textbox', { name: 'Type description here' }).click();
  await page.getByRole('textbox', { name: 'Type description here' }).fill('Automation & Manual Testing: \nSelenium Web Driver using JAVA, \nSelenium IDE, Test NG & POM, BDD With Cucumber Framework  MAVEN\nCypress with page object model using Java script is in progress.\nIntegration Testing :\nREST  API testing using POSTMAN, Swagger, Exposure with JSON, Using Different Methods and performing CRUD operations on endpoints\nWriting test cases and postman assertions with JavaScript\nRunning collection with multiple instances\nMocking APIs\nNewman for CI/CD with Jenkins-Scheduling, email notifications, Build run\nGenerating html reports with Newman \nAPI Automation testing with REST Assured library- JAVA\n \n\n\nProgramming Skills: Core Java \nOperating Systems: Windows \nCoding Platforms: Eclipse, IntelliJ \nDatabase: Basic Knowledge in MY SQL Server with SQL \nPackages: Microsoft Office\n Others: Git, Git Hub, Jenkins \nProject Management tool: JIRA, Confluence, Xray\n\n\nThe ISTQB® Foundation Level Agile Tester (CTFL-AT)');
  await page.getByText('Browse').click();
  await page.getByRole('button', { name: 'Choose File' }).setInputFiles('JIRA API Theory.txt');
  await page.getByRole('textbox', { name: 'Add note' }).click();
  await page.getByRole('textbox', { name: 'Add note' }).fill('hello');
  await page.getByRole('textbox', { name: 'Type description here' }).click();
  await page.getByRole('textbox', { name: 'Type description here' }).fill('Automation & Manual Testing: \nSelenium Web Driver using JAVA, \nSelenium IDE, Test NG & POM, BDD With Cucumber Framework  MAVEN\nCypress with page object model using Java script is in progress.\nIntegration Testing :\nREST  API testing using POSTMAN, Swagger, Exposure with JSON, Using Different Methods and performing CRUD operations on endpoints\nWriting test cases and postman assertions with JavaScript\nRunning collection with multiple instances\nMocking APIs\nNewman for CI/CD with Jenkins-Scheduling, email notifications, Build run\nGenerating html reports with Newman \nAPI Automation testing with REST Assured library- JAVA\n \nThe ISTQB® Foundation Level Agile Tester (CTFL-AT)');
  await page.getByText('BrowseJIRA API Theory.txt').click();
  await page.getByRole('button', { name: 'Choose File' }).setInputFiles([]);
  await page.getByRole('textbox', { name: 'Type description here' }).click();
  await page.getByRole('textbox', { name: 'Type description here' }).click();
  await page.getByRole('textbox', { name: 'Type description here' }).click();
  await page.getByRole('textbox', { name: 'Type description here' }).click();
  await page.getByRole('textbox', { name: 'Type description here' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Type description here' }).fill('');
  await page.getByRole('button', { name: 'Save' }).click();
});